analyzer:
  exclude:
    - build/**
    - android/**
    - windows/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: true
    prefer_const_declarations: true
    unawaited_futures: true
