import 'dart:io';

void main() {
  final emojis = [
    // 0..15: Animals - Mammals
    ('🦊', 'Fox'),
    ('🐺', 'Wolf'),
    ('🦁', 'Lion'),
    ('🐯', 'Tiger'),
    ('🐻', 'Bear'),
    ('🐼', 'Panda'),
    ('🐨', 'Koala'),
    ('🐵', 'Monkey'),
    ('🦍', 'Gorilla'),
    ('🐶', 'Dog'),
    ('🐱', 'Cat'),
    ('🐰', 'Rabbit'),
    ('🐭', 'Mouse'),
    ('🐹', 'Hamster'),
    ('🦔', 'Hedgehog'),
    ('🐿️', 'Squirrel'),

    // 16..31: Animals - Large / Safari / Sea
    ('🐘', 'Elephant'),
    ('🦒', 'Giraffe'),
    ('🦓', 'Zebra'),
    ('🐴', 'Horse'),
    ('🦌', 'Deer'),
    ('🐫', 'Camel'),
    ('🦘', 'Kangaroo'),
    ('🦏', 'Rhino'),
    ('🦛', 'Hippo'),
    ('🐳', 'Whale'),
    ('🐬', 'Dolphin'),
    ('🐙', 'Octopus'),
    ('🦈', 'Shark'),
    ('🦭', 'Seal'),
    ('🦦', 'Otter'),
    ('🦫', 'Beaver'),

    // 32..47: Animals - Birds, Reptiles & Insects
    ('🦅', 'Eagle'),
    ('🦉', 'Owl'),
    ('🐧', 'Penguin'),
    ('🦩', 'Flamingo'),
    ('🦚', 'Peacock'),
    ('🦜', 'Parrot'),
    ('🦢', 'Swan'),
    ('🦆', 'Duck'),
    ('🐢', 'Turtle'),
    ('🐸', 'Frog'),
    ('🐊', 'Crocodile'),
    ('🐍', 'Snake'),
    ('🦎', 'Lizard'),
    ('🦖', 'Dinosaur'),
    ('🦕', 'Sauropod'),
    ('🐉', 'Dragon'),

    // 48..63: Insects & Small Creatures
    ('🦋', 'Butterfly'),
    ('🐝', 'Honeybee'),
    ('🐜', 'Ant'),
    ('🐞', 'Ladybug'),
    ('🦗', 'Cricket'),
    ('🕷️', 'Spider'),
    ('🦂', 'Scorpion'),
    ('🐌', 'Snail'),
    ('🦀', 'Crab'),
    ('🦞', 'Lobster'),
    ('🦐', 'Shrimp'),
    ('🦑', 'Squid'),
    ('🦇', 'Bat'),
    ('🦡', 'Badger'),
    ('🦃', 'Turkey'),
    ('🐓', 'Rooster'),

    // 64..79: Celestial & Sky
    ('☀️', 'Sun'),
    ('🌙', 'Crescent Moon'),
    ('⭐', 'Star'),
    ('🌟', 'Glowing Star'),
    ('🌠', 'Shooting Star'),
    ('🪐', 'Saturn'),
    ('🌍', 'Earth'),
    ('☄️', 'Comet'),
    ('☁️', 'Cloud'),
    ('⚡', 'Lightning'),
    ('🌈', 'Rainbow'),
    ('❄️', 'Snowflake'),
    ('🔥', 'Fire'),
    ('🌊', 'Ocean Wave'),
    ('🌪️', 'Tornado'),
    ('🌋', 'Volcano'),

    // 80..95: Nature & Plants
    ('🏔️', 'Snow Mountain'),
    ('🏝️', 'Desert Island'),
    ('🌲', 'Evergreen Tree'),
    ('🌳', 'Deciduous Tree'),
    ('🌴', 'Palm Tree'),
    ('🌵', 'Cactus'),
    ('🌾', 'Sheaf of Rice'),
    ('🌿', 'Herb'),
    ('🍀', 'Four Leaf Clover'),
    ('🍁', 'Maple Leaf'),
    ('🍂', 'Fallen Leaf'),
    ('🍄', 'Mushroom'),
    ('🌷', 'Tulip'),
    ('🌹', 'Rose'),
    ('🌻', 'Sunflower'),
    ('🌺', 'Hibiscus'),

    // 96..111: Fruits
    ('🍎', 'Red Apple'),
    ('🍏', 'Green Apple'),
    ('🍐', 'Pear'),
    ('🍊', 'Tangerine'),
    ('🍋', 'Lemon'),
    ('🍌', 'Banana'),
    ('🍉', 'Watermelon'),
    ('🍇', 'Grapes'),
    ('🍓', 'Strawberry'),
    ('🫐', 'Blueberries'),
    ('🍒', 'Cherries'),
    ('🍑', 'Peach'),
    ('🍍', 'Pineapple'),
    ('🥥', 'Coconut'),
    ('🥝', 'Kiwi'),
    ('🥑', 'Avocado'),

    // 112..127: Vegetables & Prepared Foods
    ('🥦', 'Broccoli'),
    ('🌽', 'Ear of Corn'),
    ('🥕', 'Carrot'),
    ('🧄', 'Garlic'),
    ('🧅', 'Onion'),
    ('🥔', 'Potato'),
    ('🍞', 'Bread'),
    ('🥐', 'Croissant'),
    ('🥨', 'Pretzel'),
    ('🥯', 'Bagel'),
    ('🥞', 'Pancakes'),
    ('🧇', 'Waffle'),
    ('🧀', 'Cheese Wedge'),
    ('🍳', 'Fried Egg'),
    ('🥓', 'Bacon'),
    ('🥩', 'Cut of Meat'),

    // 128..143: Meals & Fast Food
    ('🍔', 'Hamburger'),
    ('🍟', 'French Fries'),
    ('🍕', 'Pizza'),
    ('🌭', 'Hot Dog'),
    ('🥪', 'Sandwich'),
    ('🌮', 'Taco'),
    ('🌯', 'Burrito'),
    ('🥙', 'Stuffed Flatbread'),
    ('🍿', 'Popcorn'),
    ('🍣', 'Sushi'),
    ('🥟', 'Dumpling'),
    ('🍜', 'Steaming Bowl'),
    ('🍝', 'Spaghetti'),
    ('🍲', 'Pot of Food'),
    ('🍛', 'Curry Rice'),
    ('🍱', 'Bento Box'),

    // 144..159: Sweets & Drinks
    ('🍦', 'Soft Ice Cream'),
    ('🍧', 'Shaved Ice'),
    ('🍨', 'Ice Cream Bowl'),
    ('🍩', 'Doughnut'),
    ('🍪', 'Cookie'),
    ('🎂', 'Birthday Cake'),
    ('🍰', 'Shortcake'),
    ('🧁', 'Cupcake'),
    ('🥧', 'Pie'),
    ('🍫', 'Chocolate Bar'),
    ('🍬', 'Candy'),
    ('🍭', 'Lollipop'),
    ('🍮', 'Custard'),
    ('🍯', 'Honey Pot'),
    ('☕', 'Hot Beverage'),
    ('🧃', 'Juice Box'),

    // 160..175: Transport & Vehicles
    ('🚀', 'Rocket'),
    ('🛰️', 'Satellite'),
    ('🛸', 'Flying Saucer'),
    ('🚁', 'Helicopter'),
    ('✈️', 'Airplane'),
    ('⛵', 'Sailboat'),
    ('🚤', 'Speedboat'),
    ('🚢', 'Ship'),
    ('⚓', 'Anchor'),
    ('🚗', 'Automobile'),
    ('🚕', 'Taxi'),
    ('🚌', 'Bus'),
    ('🚓', 'Police Car'),
    ('🚑', 'Ambulance'),
    ('🚒', 'Fire Engine'),
    ('🚜', 'Tractor'),

    // 176..191: Rail, Cycle & Everyday Transport
    ('🚲', 'Bicycle'),
    ('🛴', 'Kick Scooter'),
    ('🛹', 'Skateboard'),
    ('🛼', 'Roller Skate'),
    ('🚂', 'Locomotive'),
    ('🚆', 'Train'),
    ('🚇', 'Metro'),
    ('🚊', 'Tram'),
    ('🛶', 'Canoe'),
    ('🪂', 'Parachute'),
    ('🚡', 'Aerial Tramway'),
    ('🛵', 'Motor Scooter'),
    ('🏍️', 'Motorcycle'),
    ('🚨', 'Police Light'),
    ('🚥', 'Traffic Light'),
    ('⛽', 'Fuel Pump'),

    // 192..207: Tools & Hardware
    ('🔨', 'Hammer'),
    ('🪓', 'Axe'),
    ('⛏️', 'Pickaxe'),
    ('🔧', 'Wrench'),
    ('🪛', 'Screwdriver'),
    ('🔩', 'Nut and Bolt'),
    ('⚙️', 'Gear'),
    ('🧰', 'Toolbox'),
    ('🪜', 'Ladder'),
    ('🧲', 'Magnet'),
    ('💡', 'Light Bulb'),
    ('🔦', 'Flashlight'),
    ('🔋', 'Battery'),
    ('🔌', 'Electric Plug'),
    ('🧭', 'Compass'),
    ('⌛', 'Hourglass'),

    // 208..223: Science, Security & Valuables
    ('🔭', 'Telescope'),
    ('🔬', 'Microscope'),
    ('🧪', 'Test Tube'),
    ('🧬', 'DNA'),
    ('🔑', 'Key'),
    ('🔒', 'Locked Padlock'),
    ('🔓', 'Unlocked Padlock'),
    ('🛡️', 'Shield'),
    ('⚔️', 'Crossed Swords'),
    ('🏹', 'Bow and Arrow'),
    ('🎯', 'Bullseye'),
    ('👑', 'Crown'),
    ('💍', 'Ring'),
    ('💎', 'Gem Stone'),
    ('🏆', 'Trophy'),
    ('🥇', '1st Place Medal'),

    // 224..239: Arts, Music & Office
    ('🪄', 'Magic Wand'),
    ('🎨', 'Artist Palette'),
    ('🧵', 'Thread'),
    ('🧶', 'Yarn'),
    ('📷', 'Camera'),
    ('🎸', 'Guitar'),
    ('🎻', 'Violin'),
    ('🥁', 'Drum'),
    ('🎺', 'Trumpet'),
    ('🎹', 'Musical Keyboard'),
    ('🔔', 'Bell'),
    ('📣', 'Megaphone'),
    ('📖', 'Open Book'),
    ('📜', 'Scroll'),
    ('✉️', 'Envelope'),
    ('📦', 'Package'),

    // 240..255: Sports, Games, Toys & Celebration
    ('🔮', 'Crystal Ball'),
    ('🎲', 'Game Die'),
    ('♟️', 'Chess Pawn'),
    ('🧩', 'Puzzle Piece'),
    ('🪁', 'Kite'),
    ('🎈', 'Balloon'),
    ('🎉', 'Party Popper'),
    ('🪅', 'Pinata'),
    ('🎀', 'Ribbon'),
    ('🎁', 'Wrapped Gift'),
    ('⚽', 'Soccer Ball'),
    ('🏀', 'Basketball'),
    ('🏈', 'American Football'),
    ('🎾', 'Tennis'),
    ('🎳', 'Bowling'),
    ('❤️', 'Red Heart'),
  ];

  print('Count: ${emojis.length}');
  final setEmojis = <String>{};
  final setNames = <String>{};
  for (int i = 0; i < emojis.length; i++) {
    final (e, n) = emojis[i];
    if (setEmojis.contains(e)) {
      print('DUPLICATE EMOJI at $i: $e ($n)');
    }
    if (setNames.contains(n)) {
      print('DUPLICATE NAME at $i: $e ($n)');
    }
    setEmojis.add(e);
    setNames.add(n);
  }
}
